name: "Update Assets"

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Update assets

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Compile Asset
        run: |
          npm ci
          npm run prod
        env:
          TAILWIND_MODE: build

      - name: Create dist zip
        run: tar -czvf dist.tar.gz dist

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.vars.outputs.tag }}
          release_name: ${{ steps.vars.outputs.tag }}

      - name: Upload dist zip to release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist.tar.gz
          asset_name: dist.tar.gz
          asset_content_type: application/tar+gz
